MASTODON_TOKEN=${MASTODON_TOKEN}
MASTODON_INSTANCE=${MASTODON_INSTANCE}
MASTODON_TEST_USER_HANDLE=${MASTODON_TEST_USER_HANDLE}
MASTODON_TEST_HASHTAG=${MASTODON_TEST_HASHTAG}
HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
